project:
  type: website

website:
  title: "Kinematics & Dynamics"
  description: "Notes on kinematics and dynamics for robotics"
  repo-url: https://github.com/jungee-hong/KINDYN
  repo-actions: [edit, issue]
  sidebar:
    contents:
      - index.qmd
      - section: "1. 3D Rotation"
        contents:
          - text: "Introduction to 3D Rotation"
            href: intro_3d_rotation.qmd
          - text: "Paramterizating Attitude"
            href: attitude_paramterization.qmd
          - text: "Differentiable Manifold"
            href: differentiable_manifold.qmd
          - text: "Matrix Lie Group"
            href: matrix_lie_group.qmd
          - text: "Quaternion"
            href: quaternion.qmd
      - section: "2. Rotation Kinematics"
        contents:
          - text: "Angular Velocity"
            href: angular_velocity.qmd
  page-navigation: true
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
